### PR TITLE
Adds declaration and source maps.

### PR DESCRIPTION
**Pull request by MicahZoltu**
Declaration maps are like source maps, but for `.d.ts` files.  It makes it so a user who is looking at the code in an editor can press "goto definition" and be taken to actual source code rather than just seeing the declaration file.

To make this work, the source files do need to be shipped with the package.

Source maps are useful for the same reason, but for distributed JS code.  In an app that uses this library, it may be useful to have a debugger step into these libraries when troubleshooting.

### CODE REVIEW

**Comment by MicahZoltu** [comment]
Updated to correctly include the right files in `package.json` for publishing.  Since this project targets both ESM and CJS, we need separate declaration files and source maps for each (since the compiled output may differ, and the targeting may be different).

**Comment by paulmillr** [comment]
Could you measure package size before and after the change?

**Comment by paulmillr** [comment]
Because if we do a change like this, we will need to do a similar change for all 5 `ethereum-cryptography` dependencies and `ethereum-cryptography` itself. Otherwise, why stop on just one package?

What about BIP39 wordlists? Will we need to create declaration maps for them too, and include wordlist typescript files? Wordlists are huge, including them twice would not be great.

**Comment by MicahZoltu** [comment]
Results below.  My recommendation would be to take special measures with anything that includes something like a wordlist, for the exact reason you mentioned.  Worst case scenario, you can apply this to all of the repositories that are "reasonable" without special consideration (like this one IMO), and put off or potentially never apply these changes to anything that includes something like a wordlist.

main:
```
npm notice === Tarball Contents ===
npm notice 1.1kB LICENSE
npm notice 3.8kB README.md
npm notice 9.0kB lib/esm/index.js
npm notice 62B   lib/esm/package.json
npm notice 1.5kB lib/index.d.ts
npm notice 9.4kB lib/index.js
npm notice 1.7kB package.json
npm notice === Tarball Details ===
npm notice name:          @scure/bip32
npm notice version:       1.1.0
npm notice filename:      @scure/bip32-1.1.0.tgz
npm notice package size:  6.1 kB
npm notice unpacked size: 26.6 kB
npm notice shasum:        bff483404befa3eae63e1ad965e46a164782f5a4
npm notice integrity:     sha512-heQABGJqo0pzq[...]6z4Yf0xNnqBtQ==
npm notice total files:   7
```
patch-1
```
npm notice === Tarball Contents ===
npm notice 1.1kB  LICENSE
npm notice 3.8kB  README.md
npm notice 9.7kB  index.ts
npm notice 1.5kB  lib/esm/index.d.ts
npm notice 1.5kB  lib/esm/index.d.ts.map
npm notice 9.1kB  lib/esm/index.js
npm notice 19.5kB lib/esm/index.js.map
npm notice 62B    lib/esm/package.json
npm notice 1.5kB  lib/index.d.ts
npm notice 1.5kB  lib/index.d.ts.map
npm notice 9.5kB  lib/index.js
npm notice 19.4kB lib/index.js.map
npm notice 1.8kB  package.json
npm notice === Tarball Details ===
npm notice name:          @scure/bip32
npm notice version:       1.1.0
npm notice filename:      @scure/bip32-1.1.0.tgz
npm notice package size:  12.0 kB
npm notice unpacked size: 80.0 kB
npm notice shasum:        33bcca1d6b9cf6f9682187f5e530a9e29dd32ab8
npm notice integrity:     sha512-rRYtwuldWacIh[...]PIyi0sGl4SqBg==
npm notice total files:   13
```

**Comment by paulmillr** [comment]
I've started using maps — good stuff, but will probably defer this to the time we'll drop common.js.

**Pull request closed without merging**
